### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by micahpearlman** [llSourcell/Drone_Flight_Controller#2]
Getting the following output.  Note that it does successfully connect to the DroneSim.

```
robond@udacity:~/dev/catkin_ws$ roslaunch quad_controller_rl rl_controller.launch
... logging to /home/robond/.ros/log/1c9dda62-e3c2-11e8-99ba-000c2968920d/roslaunch-udacity-6400.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://172.16.50.128:41069/

SUMMARY
========

PARAMETERS
 * /agent: RandomPolicySearch
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /task: Takeoff

NODES
  /
    drone_sim (quad_controller_rl/drone_sim)
    rl_controller (quad_controller_rl/rl_controller_node)

auto-starting new master
process[master]: started with pid [6411]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1c9dda62-e3c2-11e8-99ba-000c2968920d
process[rosout-1]: started with pid [6424]
started core service [/rosout]
ERROR: cannot launch node of type [quad_controller_rl/rl_controller_node]: can't locate node [rl_controller_node] in package [quad_controller_rl]
ERROR: cannot launch node of type [quad_controller_rl/drone_sim]: can't locate node [drone_sim] in package [quad_controller_rl]
```

**Comment by AloshkaD** [comment]
@micahpearlman  Same error here, have you fixed it?

**Comment by micahpearlman** [comment]
@AloshkaD I have not.

**Comment by AloshkaD** [comment]
@micahpearlman I've just solved it. Simply change the permission for the entire directory to read, write, and execute like this.
`sudo chmod -R 777 catkin_ws`

**Comment by Charelvanhoof** [comment]
What sudo password? Could not find where I can get/set it

**Comment by hamoda150** [comment]
I have the same problem. but it shows another error

`Traceback (most recent call last):
  File "/home/robond/catkin_ws/src/RL-Quadcopter/scripts/rl_controller_node", line 8, in <module>
    import rospy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 47, in <module>
    import yaml
ImportError: No module named 'yaml'
[rl_controller-1] process has died [pid 4035, exit code 1, cmd /home/robond/catkin_ws/src/RL-Quadcopter/scripts/rl_controller_node __name:=rl_controller __log:=/home/robond/.ros/log/e4bf2eca-fa73-11e8-bd30-000c2949cc71/rl_controller-1.log].
log file: /home/robond/.ros/log/e4bf2eca-fa73-11e8-bd30-000c2949cc71/rl_controller-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
`

**Comment by AloshkaD** [comment]
@hamoda150 
You have
```ImportError: No module named 'yaml'``` 
check that out to see if you are missing anything

**Comment by hamoda150** [comment]
@AloshkaD 
I already installed it with this command
`sudo pip install pyyaml`
but it still show this error

**Comment by AloshkaD** [comment]
@hamoda150 from the error message you have, clearly it could not be found in the system. It could be that the path was not set correctly. Check that it's installed correctly by typing in "python" in terminal and then "import yaml" or create a conda env and have everything installed via anaconda.

**Comment by hiyoit** [comment]
I found an error in  master.log

``[rosmaster.threadpool][ERROR] 2021-04-24 22:22:39,391: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 208, in publisher_update_task
    xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])

**Fault: <Fault -1: 'publisherUpdate: unknown method name'>**

**Comment by FromClc** [comment]
Then, I have another problem 
ImportError: No module named 'rospkg'

so ,I think I  should install the py depences for ros.

**Comment by hiyoit** [comment]
I solved this error.
I git clone the source of arbotix in github ,howerver,on 2021.4.25 ,the source of arbotix in github is for neotic. 
The version of my ros is kinetic.

Try :
`sudo apt-get install ros-kinetic-arbotix`

you can change the version name of your ros.
